# Cloud Build - Firebase Hosting 자동 배포
# Trigger: Push to main branch
# 설정: GCP Console → Cloud Build → Triggers

steps:
  # 1. 의존성 설치
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['ci']

  # 2. Next.js 빌드 (환경변수는 Secret Manager에서 주입)
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
    secretEnv:
      - 'NEXT_PUBLIC_FIREBASE_API_KEY'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID'
      - 'CLOUD_RUN_ORCHESTRATOR_URL'
      - 'TRIGGER_SECRET_KEY'
      - 'GOOGLE_API_KEY'

  # 3. Firebase Hosting 배포
  - name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project templar-archives-index
    secretEnv:
      - 'FIREBASE_TOKEN'

# Secret Manager 연결
# 사전 설정 필요: gcloud secrets create SECRET_NAME --data-file=-
availableSecrets:
  secretManager:
    # Firebase Client Config (NEXT_PUBLIC_*)
    - versionName: projects/templar-archives-index/secrets/NEXT_PUBLIC_FIREBASE_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_API_KEY'
    - versionName: projects/templar-archives-index/secrets/NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/templar-archives-index/secrets/NEXT_PUBLIC_FIREBASE_PROJECT_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
    - versionName: projects/templar-archives-index/secrets/NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/templar-archives-index/secrets/NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/templar-archives-index/secrets/NEXT_PUBLIC_FIREBASE_APP_ID/versions/latest
      env: 'NEXT_PUBLIC_FIREBASE_APP_ID'

    # Backend Services
    - versionName: projects/templar-archives-index/secrets/CLOUD_RUN_ORCHESTRATOR_URL/versions/latest
      env: 'CLOUD_RUN_ORCHESTRATOR_URL'
    - versionName: projects/templar-archives-index/secrets/TRIGGER_SECRET_KEY/versions/latest
      env: 'TRIGGER_SECRET_KEY'
    - versionName: projects/templar-archives-index/secrets/GOOGLE_API_KEY/versions/latest
      env: 'GOOGLE_API_KEY'

    # Firebase CI Token (firebase login:ci 로 생성)
    - versionName: projects/templar-archives-index/secrets/FIREBASE_TOKEN/versions/latest
      env: 'FIREBASE_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # 빌드 속도 향상
